### ISSUE TITLE
I can't see example

### ISSUE THREAD

**Issue by chengfengfengwang** [jotai-labs/jotai-tutorial#41]
**Describe the bug**

Can't see example.
iframe show error:  'react-dom.development.js:798 Error: <svg> attribute viewBox: Expected number, "0 0 100'

**To Reproduce**

1. Go to 'https://tutorial.jotai.org/quick-start/write-only-atoms'
2. See error

**Screenshots**
<img width="1492" alt="image" src="https://github.com/jotaijs/jotai-tutorial/assets/23279667/9f8d4636-fffd-4fe2-821c-719521670bb2">

**Desktop (please complete the following information):**

- OS: [mac OS Ventura M1 Pro ]
- Browser [chrome]
- Version [124.0.6367.156 (Official Build) (arm64)]

**Comment by vasucp1207** [comment]
> **Describe the bug**
> 
> Can't see example. iframe show error: 'react-dom.development.js:798 Error: attribute viewBox: Expected number, "0 0 100'
> 
> **To Reproduce** Steps to reproduce the behavior:
> 
> 1. Go to 'https://tutorial.jotai.org/quick-start/write-only-atoms'
> 2. See error
> 
> **Screenshots** <img alt="image" width="1492" src="https://private-user-images.githubusercontent.com/23279667/329545967-9f8d4636-fffd-4fe2-821c-719521670bb2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY0NzUzMjAsIm5iZiI6MTcxNjQ3NTAyMCwicGF0aCI6Ii8yMzI3OTY2Ny8zMjk1NDU5NjctOWY4ZDQ2MzYtZmZmZC00ZmUyLTgyMWMtNzE5NTIxNjcwYmIyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTIzVDE0MzcwMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE2OTY3NWQ3ZjUxYWM4OGZjZjllZGQ3MjQ0OGQ1M2MyMTY5MThhNmNlMTExZjAyMjIxMTY2ZjY1NjA0MzUxODgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.5AtGz7rKCsMs09TfhVSPjsV4pRjAKfUQ2fEnBV2iGIs">
> 
> **Desktop (please complete the following information):**
> 
> * OS: [mac OS Ventura M1 Pro ]
> * Browser [chrome]
> * Version [124.0.6367.156 (Official Build) (arm64)]

Drag the mouse on the canvas, it's working properly.

<img width="883" alt="Screen Shot 2024-05-23 at 8 09 43 PM" src="https://github.com/jotaijs/jotai-tutorial/assets/85363195/c4bf903f-6cfb-46ee-87a8-61d2af7fbd20">
